name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
       node-version: '14'
    - name: Build bitwise
      run: yarn run build
  jest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
       node-version: '14'
    - name: Test bitwise
      run: yarn run test
    - name: Build bitwise
      run: yarn run build
  yarn:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
       node-version: '14'
    - name: Check modules
      run: yarn install --immutable --immutable-cache
